# -*- coding: utf-8 -*-
"""GAME DEVELOPMENT BY CREWAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Twz9NyLPIMftBw_X0j6yAnCm5GU8UhnC
"""

# !pip install crewai

# !pip install "crewai[google-genai]"
# !pip install crewai['tools']


from crewai import Agent,LLM,Task,Crew,Process
import os
from dotenv import load_dotenv
load_dotenv()
from crewai_tools import SerperDevTool

llm = LLM(
    model="gemini-2.5-flash",
    api_key=os.getenv('my_api')
)

#AGENT (GAME DESIGNER)
game_designer = Agent(
    role="Creative Game Designer",
    goal="Come up with fun, feasible game concepts and detailed mechanics based on user idea",
    backstory=(
        "You are an experienced game designer.\n"
        "You excel at turning vague ideas into clear, exciting game designs including:\n"
        "- core loop, rules, win/lose conditions\n"
        "- basic entities (player, enemies, items)\n"
        "- controls and feel\n"
        "Keep it simple enough to implement in pure Python + Pygame in one file."
    ),
    llm=llm,
    verbose=True
)

serper_api_key = os.getenv('serp_api')
search_tool = SerperDevTool(
    api_key=serper_api_key
    )

#AGENT (SENIOR_ENGINEER)
senior_engineer = Agent(
    role="Senior Python Game Developer",
    goal="Write clean, working Python code (using Pygame) for the described game",
    backstory=(
        "You are a senior software engineer specialized in Python game development with Pygame.\n"
        "You write structured, readable code with:\n"
        "- Proper game loop, event handling, drawing\n"
        "- Comments explaining key parts\n"
        "- Error handling where needed\n"
        "You always produce a complete, runnable .py file."
    ),
    llm=llm,
    verbose=True,
    tools=[search_tool]
)

qa_engineer = Agent(
    role="QA Engineer & Code Reviewer",
    goal="Test, review, and improve the code for bugs, playability, and completeness",
    backstory=(
        "You are a meticulous QA engineer and code reviewer.\n"
        "You carefully check:\n"
        "- Does the code run without errors?\n"
        "- Does it implement ALL the designed features?\n"
        "- Is it fun/playable? Any obvious balance issues?\n"
        "- Code style, variable names, comments\n"
        "Suggest fixes or small improvements and output the FINAL improved code."
    ),
    verbose=True,
    llm=llm
)

#now we have to assign the tasks for each agent
# GAME Designer Agent task

game_design_task=Task(

description=(
    "Take the user's game idea: {game_idea}\n"
    "1. Clarify and expand it into a fun, simple 2D game\n"
    "2. Describe: objective, controls, entities, win/lose\n"
    "3. Keep scope small (one level, basic mechanics)\n"
    "Output format:\n"
    "## Game Design Document\n"
    "- Title: ...\n"
    "- Genre: ...\n"
    "- Objective: ...\n"
    "- Controls: ...\n"
    "- Entities: ...\n"
    "- Mechanics: ..."
),
expected_output="A clear markdown Game design Document",
agent=game_designer)

#now we are defining a task for senior engineer
#task as code
task_code = Task(
    description=(
        "Using the game design from the previous task\n"
        "Write a COMPLETE, standalone Python script using Pygame that implements the game.\n"
        "- Include import pygame, sys, random (if needed)\n"
        "- Full game loop, init, events, update, draw\n"
        "- Make it runnable with python game.py\n"
        "- Add simple comments\n"
        "- The main game loop must be exposed in the python code, it should not be inside any function like main\n"
        "- Final answer MUST be ONLY the Python code and Instructions on how to play the game"
    ),
    expected_output="A complete runnable Pygame python script",
    agent=senior_engineer,
    context=[game_design_task]
)

#now we are defining review task for QA engineer
task_review = Task(
    description=(
        "Review the Python code from the previous task.\n"
        "1. Check for syntax/runtime errors\n"
        "2. Verify it matches the design document\n"
        "3. Test mentally: does it have init, loop, quit handling, drawing?\n"
        "4. Suggest fixes/improvements if needed\n"
        "5. Output the FINAL, improved, ready-to-run code\n"
        "Your final answer MUST be ONLY the complete Python code along with the instructions on how to play the game"
    ),
    expected_output="Final polished, runnable Pygame Python script and instructions on how to play the game",
    agent=qa_engineer,
    context=[task_code,game_design_task]
)

game_crew = Crew(
    agents=[game_designer, senior_engineer, qa_engineer],
    tasks=[game_design_task, task_code, task_review],
    process=Process.sequential,
    verbose=True
)

game_idea = "A fun endless runner where a character jumps over obstacles"
result = game_crew.kickoff(inputs={"game_idea": game_idea})

# Convert result to string before writing to handle potential non-string outputs from failed tasks
output_to_write = str(result)

# Write the generated game code or error output to main.py
with open("main.py", "w") as f:
    f.write(output_to_write)

print("Game code or CrewAI output written to main.py")
print(output_to_write)

"""DON'T CHANGE ANYTHING BELOW THIS LINE"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# #we should write code here


ngrok_auth_token = os.getenv("NGROK_AUTH_TOKEN")

#pip install pygbag pyngrok  -q

import subprocess
import time
from pyngrok import ngrok
import os

print("🔨 Building game...")
import sys

build_result = subprocess.run(
    [
        sys.executable,
        "-m",
        "pygbag",
        "--build",
        "--version",
        "0.9",
        "--PYBUILD",
        "3.12",
        "--cdn",
        "https://pygame-web.github.io/archives/0.9/",
        ".",
    ],
    capture_output=True,
    text=True,
)

print(build_result.stdout)

if build_result.returncode != 0:
    print("❌ Build failed:")
    print(build_result.stderr)
else:
    print("✅ Build successful!")

    print("\n🚀 Starting server...")
    server = subprocess.Popen(
        [
            "python",
            "-m",
            "http.server",
            "8000",
            "--directory",
            "/content/build/web",
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    time.sleep(5)

    try:
        print("🌐 Creating public URL...")
        public_url = ngrok.connect(8000)

        print("\n" + "=" * 60)
        print("👾 YOUR GAME IS READY!")
        print("=" * 60)
        print(f"\n🔗 Click here to play: {public_url}")
        print("\n📝 How to play:")
        print(" • Press SPACE or Click to jump")
        print("=" * 60)

    except Exception as e:
        print(f"\n❌ Error creating tunnel: {e}")
        print("\n💡 Make sure you ran Cell 3 with a valid ngrok token")